apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: practice
spec:
  strategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.1
        resources:
          limits:
            cpu: "300m"
          requests:
            cpu: "200m"