apiVersion: v1
kind: Pod
metadata:
  name: nginx-practice
  namespace: practice
  labels:
    version: "3.0"

spec:
  containers:
    - name: nginx-practice-container
      image: nginx:1.20.2
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
          hostPort: 80
