apiVersion: v1
kind: Service
metadata:
  name: nginx-service-node
  namespace: practice

spec:
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30080
  selector:
    app: nginx-pod
  type: NodePort
  sessionAffinity: None
