apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: practice

spec:
  clusterIP: 10.96.0.100
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-pod
  type: ClusterIP
